spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adquisicion?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: juaMAR1306
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 8080

