spring:
  datasource:
    url: jdbc:mysql://localhost:3308/adquisicion2?allowPublicKeyRetrieval=true&useSSL=false
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 8080

