spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/adquisicion2?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


server:
  port: 8080

